server:
  port: 9090
  servlet:
    context-path: /spring-batch

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    continue-on-error: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    jpa.repositories.enabled: true

  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: always